exam2 : main.o add.o minus.o multiple.o devide.o
	gcc -o exam2 main.o add.o minus.o multiple.o devide.o
main.o : main.c
	gcc -c main.c
add.o : add.c
	gcc -c add.c
minus.o : minus.c
	gcc -c minus.c
multiple.o : multiple.c
	gcc -c multiple.c
devide.o : devide.c
	gcc -c devide.c
clean : 
	rm -f exam2 main.o add.o minus.o multiple.o devide.o
